### ISSUE TITLE
How do I print the glossary?

### ISSUE THREAD

**Issue by MariusWiik** [egraff/uit-thesis#65]
I've defined acronyms and glossary entries in the main thesis.tex file and I want the links that are created to go to a glossary page. I've tried \printglossaries and \printglossary at the end but nothing shows up. 
Any ideas?

**Comment by egraff** [comment]
The most common reasons for "List of Abbreviations" or glossaries not being output is either forgetting to include `\makeglossaries` in the preamble, or forgetting to run either `makeglossaries`or `xindy` (as is required by the [glossaries](https://ctan.org/pkg/glossaries) package - see http://ctan.uib.no/macros/latex/contrib/glossaries/glossaries-user.html).

However, in addition, the `\printglossaries` command is disabled in the uit-thesis template, so you'll need to use `\printglossary` for each specific glossary you want to show. For "List of Abbreviations", use `\printglossary[type=\acronymtype]` or `\printacronyms` (the latter is equivalent to `\printglossary[type=\acronymtype,style=ult-list]`).

The following is an MWE that demonstrates this:

```latex
\documentclass{uit-thesis}

\makeglossaries

\newacronym{api}{API}{application programming interface}
\newglossaryentry{something}
{
  name=something,
  description={%
    a description%
  },
}

\begin{document}

\frontmatter
\tableofcontents
\printacronyms

\mainmatter

\chapter{A chapter}
A sentence referring to an \ac{api}.

Referencing \gls{something}.

\printglossary[style=ult-list]

\backmatter

\end{document}

```

**Comment by MariusWiik** [comment]
Thanks, `\printacronyms` for acronyms and `\printglossary` for glossary seems to work perfectly.
