### ISSUE TITLE
Får ikke installert på Windows

### ISSUE THREAD

**Issue by paalge** [egraff/uit-thesis#68]
Hei

Vi har noen studenter her på IVT som vil installere det på Windows.
Installeren spør etter HTTP proxy

**Comment by egraff** [comment]
Takk for tilbakemelding!
Skal prøve å få dette fikset så fort som mulig.

(Tracked issue: https://github.com/egraff/uit-thesis-installer/issues/1)

**Comment by paalge** [comment]
Takk, du får si fra hvis du ønsker hjelp å vedlikeholde.

**Comment by egraff** [comment]
@paalge Skal være fikset nå. Ny installer er tilgjengelig her:
https://github.com/egraff/uit-thesis-installer/releases/tag/v2.0.

Gi gjerne tilbakemelding på om dette løser problemet for deg 🙂

**Comment by paalge** [comment]
Takk for rask tilbakemelding. Skal teste det og komme tilbake.
En heads up. UiT har byttet noen av logoene og gjort om på noe av designet, snakket med de ansvarlige i dag, og kan hende de sender inn en Issue.

**Comment by paalge** [comment]
Har testet litt, men endte med å måtte pakke ut exe filen (grunnet policy på UiT), og fikk dette:
.\usr\bin\sh.exe .\setup-ult.sh

-------------------------------------------------------
Fetching the latest UiT thesis LaTeX template revision
-------------------------------------------------------
Initialized empty Git repository in /.git/
.\usr\bin\sh.exe : From https://github.com/egraff/uit-thesis
At line:1 char:1
+ .\usr\bin\sh.exe .\setup-ult.sh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (From https://gi...raff/uit-thesis:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
 * [new branch]      master     -> origin/master

-------------------------------------------------------
Checking out the uit-thesis master branch
-------------------------------------------------------
Submodule '
ult-base' (https://github.com/egraff/ult-base.git) registered for path 'ult-base'
fatal: could not create leading directories of '//ult-base': No such file or directory
fatal: clone of 'https://github.com/egraff/ult-base.git' into submodule path '//ult-base' failed
Failed to clone 'ult-base'. Retry scheduled
fatal: could not create leading directories of '//ult-base': No such file or directory
fatal: clone of 'https://github.com/egraff/ult-base.git' into submodule path '//ult-base' failed
Failed to clone 'ult-base' a second time, aborting


-------------------------------------------------------
Installing UiT thesis LaTeX template
-------------------------------------------------------

**Comment by egraff** [comment]
@paalge `.\usr\bin\sh.exe .\setup-ult.sh` ville vanligvis være riktig, men i dette tilfellet forventer setup-ult.sh å bli kjørt fra rota til MSYS2-filsystemet, så du må faktisk kjøre `.\usr\bin\sh.exe /setup-ult.sh` istedet

**Comment by paalge** [comment]
Forstår jeg at det må ligge på C: da? Hvis ikke,får jeg samme feil igjen med den nye kommandoen.
Jeg prøvde også exe filen i en test VM av Windows 10 og den klarte submodule, men fikk en feil at den ikke fant texmf folder:

Cannot locate your home texmf tree. Specify manually with                                                                                                                                                                                           make install TEXMF=/path/to/texmf                                                                                                                                                                                                           make: *** [Makefile:37: try-texmf-local] Error 1     

Kjører jeg den utpakkede filen via kommando i VMen får jeg samme feil med submodule og texmf

**Comment by egraff** [comment]
> Forstår jeg at det må ligge på C: da?

Nei, det stemmer ikke - men jeg ser imidlertid at jeg var litt for rask i svingene når jeg svarte deg, så kommandoen ble ikke helt rett. Har dobbeltsjekket nå, og følgende burde fungere:

Når du pakker ut exe-fila, må du passe på å pakke den ut til en egen katalog (f. eks. ei mappe som heter "uit-thesis-install"). Det burde ikke ha noe å si hvor mappa ligger, men etter å ha pakket ut installeren skal denne mappa inneholde en annen mappe som heter "ultinstaller-tmp". Når man så skal kjøre setup-kommandoen må dette gjøres fra "uit-thesis-install"-mappa (hvis man kjører den inni "ultinstaller-tmp"-mappa går det galt). Altså er riktig kommando:

```
.\ultinstaller-tmp\usr\bin\sh.exe /setup-ult.sh
```

> Jeg prøvde også exe filen i en test VM av Windows 10 og den klarte submodule, men fikk en feil at den ikke fant texmf folder:
> 
> Cannot locate your home texmf tree. Specify manually with make install TEXMF=/path/to/texmf make: *** [Makefile:37: try-texmf-local] Error 1

Denne feilen hadde jeg glemt litt av da jeg fikset installeren. Det skyldes en ganske ergerlig regresjon i nyere versjoner av MiKTeX (jeg holder faktisk på akkurat nå å se på dette problemet). Kort fortalt, så må du lage deg en egen texmf-mappe et sted på disken din (anbefaler f.eks. å kalle den "texmf" og legge den i `%userprofile%`), og legge den til som en bruker-definert "TEXMF root directory" i MiKTeX Console:

![miktex-console](https://user-images.githubusercontent.com/5569523/68435073-d0fce180-01ba-11ea-8c27-27e522e744bc.PNG)

Etter at dette er gjort burde installeren klare å finne texmf-mappa av seg selv. Hvis du ønsker å verifisere, kan du prøve å kjøre `kpsewhich --var-value TEXMFHOME` fra et kommandolinje-vindu (denne kommandoen burde da returnere full path til texmf-mappa di).

**Comment by egraff** [comment]
@paalge Jeg har bygd en ny installer (https://github.com/egraff/uit-thesis-installer/releases/tag/v2.0.1), som nå inkluderer et script `install.bat` for å gjøre det enklere å installere malen hvis man har behov for å pakke ut exe-fila manuelt, istedet for å kjøre den direkte (som i ditt tilfelle). Det nye `install.bat`-scriptet vil kjøre riktig `sh`-kommando, så man skal slippe å tenke på den 🙂

**Comment by paalge** [comment]
@egraff Da fikk jeg det installert etter å ha lagt til mappen i MikTex. Takk for hjelpen.

**Comment by egraff** [comment]
@paalge så bra!

Apropos, i og med at det høres ut som du har en nokså ny versjon av MiKTeX, så tenkte jeg å informere deg om et annet problem du mest sannsynlig kommer til å støte på. På grunn av en oppdatering i `opensans`-pakken som har brekt bakoverkompatibilitet, så lastes ikke Open Sans-fonten slik den skal. Resultatet er at det som f.eks. skulle sett slik ut:

<a href="http://egraff.github.io/uit-thesis/travis-builds/212.1/proto/test_frontpage_copyright_1.png"><img src="http://egraff.github.io/uit-thesis/travis-builds/212.1/proto/test_frontpage_copyright_1.png" width="48%"></a> og <a href="http://egraff.github.io/uit-thesis/travis-builds/212.1/proto/test-geometry-different-textwidth_1.png"><img src="http://egraff.github.io/uit-thesis/travis-builds/212.1/proto/test-geometry-different-textwidth_1.png" width="48%"></a>

for øyeblikket istedet ser slik ut:

<a href="http://egraff.github.io/uit-thesis/travis-builds/212.1/tests/test_frontpage_copyright_1.png"><img src="http://egraff.github.io/uit-thesis/travis-builds/212.1/tests/test_frontpage_copyright_1.png" width="48%"></a> og <a href="http://egraff.github.io/uit-thesis/travis-builds/212.1/tests/test-geometry-different-textwidth_1.png"><img src="http://egraff.github.io/uit-thesis/travis-builds/212.1/tests/test-geometry-different-textwidth_1.png" width="48%"></a>

Dette er imidlertid noe jeg holder på å jobbe med nå, og tror jeg har en fiks klar i løpet av et par dager (tracker problemet i pull request #67).

Ang. ny grafisk profil til UiT, så er dette såklart veldig interessant å prøve å få på plass i en ny versjon av malen 🙂

**Comment by paalge** [comment]
Jeg arbeider på Linux, men studentene som jeg skal undervise  i LaTeX bruker windows, så måtte ha noe å vise til de. 
Takk for alt arbeidet

**Comment by egraff** [comment]
Skjønner! Problemet jeg nevnte tidligere ville imidlertid være det samme også med en nyere TeX Live-distribusjon (eller forsåvidt en eldre, men med oppdaterte pakker). Men det problemet har nå blitt fikset! 🙂
