### ISSUE TITLE
New theses template

### ISSUE THREAD

**Issue by llu025** [egraff/uit-thesis#70]
Hello,

UiT recently went through a restyiling process and, among other things, updated the templates for assignments and theses, for which they only provide a Word document..
Is there any hope that this Latex package will be updated in the near future?
Thank you!

**Comment by egraff** [comment]
Hi,

We are trying to get hold of new vector graphics from UiT. Unfortunately, I don't have any more information about when this will be available, but I'm hoping for sooner rather than later.

**Comment by jonjohansen** [comment]
> Hi,
> 
> We are trying to get hold of new vector graphics from UiT. Unfortunately, I don't have any more information about when this will be available, but I'm hoping for sooner rather than later.

Hey 👋 
Starting to close in on this semesters deadline. 
Is there any updates on the vector graphics? 
Which ones are you missing?

**Comment by egraff** [comment]
I've obtained the new vector graphics, and am currently working to adapt the template to the new UiT brand. So far, the front page is complete, and I need to add a back page, and update the color scheme and/or change the chapter headings.

**Comment by egraff** [comment]
Everything has been merged back to master now.
Moving remaining documentation tasks to #73.
