### ISSUE TITLE
Støtte for biblatex referansehåndtering

### ISSUE THREAD

**Issue by Chemostratigrapher** [egraff/uit-thesis#77]
Hei!

Tenkte å benytte meg av denne flotte malen til min PhD-avhandling ved UiT, men forstår ikke hvordan man kan referere ved å bruke biblatex + biber til referansehåndtering. Er disse løsningene støttet i denne malen? Ser ikke ut som om biblatex kalles på i uit-thesis.cls eller i thesis.tex.

Takk for svar på forhånd, og innsatsen som er lagt ned i å opprette og vedlikeholde malen!

Mvh,
Fredrik Wesenlund

**Comment by fjukstad** [comment]
Det høres ut som en veldig god ide å bruke malen til doktoravhandlingen din! Jeg gjorde det samme og har lagt den her: https://github.com/fjukstad/thesis. Ta en titt på [Makefile](https://github.com/fjukstad/thesis/blob/master/Makefile) for å se hvordan jeg bygget en PDF fra diverse `.tex` og `.bib` filer.

**Comment by Chemostratigrapher** [comment]
Hei, og takk for raskt svar! Jeg benytter meg av latexmk via Texstudio som ser ut til å fungere fint til å bygge pdfen. Kom frem til at jeg kunne legge ved biblatex i thesis.tex eksempelfil og ordne refereansestil til authoryear, som er standarden for geovitenskapelige publikasjoner. Alt ser ut til å fungere fint nå.

Takk for hjelpen!

Mvh,
Fredrik
