### ISSUE TITLE
Overleaf + last version for PhD

### ISSUE THREAD

**Issue by sakh251** [egraff/uit-thesis#79]
Hello and Thank you for your repository,

I tried to put your code on Overleaf. It works and I can make it run for the master thesis. However for PhDs. I checked and it seems in the last version you have not included phd class option (I checked uit-thesis.cls). I checked previous versions and made it work on overleaf, again it works but for phd, the title is on the first page and the logo and figures on the front page go to the second page. 
Anyway, could you please tag a version that can be used for phd with the last updates? Or please help to make it run on Overleaf for phds.  

Thank you very much!

**Comment by egraff** [comment]
What kind of change did you do? As far as I'm aware, there isn't a separate front page design for PhD theses anymore - it's the same front page and colors for both PhD and master theses with the current UiT design profile.

**Comment by sakh251** [comment]
oh, I am not sure about it. I will double-check it. 

the master branch works fine on overleaf.
Thank you!
