### ISSUE TITLE
Overleaf error

### ISSUE THREAD

**Issue by pguio** [egraff/uit-thesis#82]
Hi again,
Do you have any idea how to fix this error in overleaf

Class uit-thesis Error: BUG! Assumption was that original atbegshi package is not in use when new lthooks system is used.

Many thanks,
Patrick

**Comment by egraff** [comment]
Yes, this was a regression that I've recently fixed. You simply need to download (or clone) the latest version of the thesis template from git! 🙂

**Comment by pguio** [comment]
Thank you all done!
