### ISSUE TITLE
Many warnings

### ISSUE THREAD

**Issue by pguio** [egraff/uit-thesis#85]
I tried to compile my Master student's project on overleaf and I noticed a very long list of warnings (80 warnings), many of them from microtype package:
Package microtype Warning: tracking amount list `output.tex/55' will override list 
Is there a way to avoid them?

**Comment by NilsBochow** [comment]
did you manage to fix it?

**Comment by pguio** [comment]
I never got an answser or suggestion.

**Comment by jaalu** [comment]
As a workaround, you can manually suppress the `microtype` warnings in `uit-thesis.cls` by setting `verbose=silent` in line 714 of `uit-thesis.cls`:

```
\usepackage[activate={true,nocompatibility},final,kerning=true,spacing=true,factor=1100,stretch=10,shrink=10,verbose=silent]{microtype}
```

https://github.com/egraff/uit-thesis/blob/338297d50a63e6d879e85003f6e73856da0c895c/texmf-tds/tex/latex/uit-thesis/uit-thesis.cls#L714

**Comment by egraff** [comment]
I'm sorry I haven't replied to this, I must have completely missed it.

If the microtype package outputs a warning, it means (unless there is a bug in the template, for example for list environments, etc.) that there is a problem with the document itself that one should attempt to fix. Such warnings are analogous to the typical underfull/overfull hbox warnings from LaTeX itself when the TeX hyphenation and line-breaking algorithms are unable to satisfy the minimum "badness" requirements. I'll defer to the microtype package documentation for how to adress these warnings.
