### ISSUE TITLE
TexLive 2024?

### ISSUE THREAD

**Issue by ruzko** [egraff/uit-thesis#86]
Thanks so much for maintaining this document class!

I had a great time using it on TexLive 2023 previously.
TexLive 2024 is released, are you planning to test against it in CI?

I've tried using this class for v2024, but any basic document using the uit-thesis class fails to compile on my installation of texlive 2024.

The error from console:
`document.tex: feil: 9: Package ult-custom-listings Error: Failed to patch \lst@MakeCaption. \begin{document}`

Complete log is attached
[document.log](https://github.com/egraff/uit-thesis/files/14891221/document.log)

Environment:
OS: Fedora Linux Atomic 40
texlive installed as flatpak, [org.freedesktop.Sdk.Extension.texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive) branch 23.08.
Editors: tried various editors (TexMaker, TexStudio, Kile, Setzer).

**Comment by egraff** [comment]
Hey, @ruzko!

The CI always tests against the latest TeX Live in addition to the older stable/finalized releases. I did some "janitor work" a couple of weeks ago to update the names of the builds and the corresponding config files to reflect that "latest" is indeed TL2014. I also noticed and fixed the error you mentioned at the same time. Make sure you pull the latest version of uit-thesis, update the submodule (ult-base), and then try to reinstall. Although the last CI run from yesterday has some redness on Windows (which I've yet to look into), the last TL2014 Linux run was green: https://ci.appveyor.com/project/egraff/uit-thesis/branch/master/job/fqg6adut3ym695aw

Note that at any given time, the latest version of TL (currently 2024) should be regarded (IMHO) as an unstable release as long as it is not frozen and is open to changes via CTAN. And although I try to make sure the uit-thesis template works with the latest version, it can easily break, and I don't always have time to fix problems immediately (and sometimes they can be quite difficult and time consuming to triage correctly and then fix).

**Comment by ruzko** [comment]
Thanks for the fast and comprehensive reply, @egraff!

I noticed that you had updated the repos, so I did a regular `git pull` before opening this issue. But that doesn't seem to have correctly updated the `ult-base` submodule, among other possible things.
Did another `git pull` today, which gave an error `could not find file 'ult-glossaries-casechange-fix.sty'`.

[Did some digging online](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_pulling_upstream_changes_from_the_project_remote), and found that doing `git submodule update --recursive --remote` pulls the latest changes from submodules as well. After pulling the latest submodule changes, everything works like a charm with TL2024!
Thanks a bunch!

re viability of the latest TL release; I didn't update to TL2024 of my own will, it's just that all the TeX editor apps on Flathub rely on a specific runtime to provide TL, and that runtime updated to TL2024 two weeks ago :sweat_smile: 

---

ps. Do you mind if I open a PR to add `git pull && git submodule update --init --recursive` in the Readme under a "How to update" header?
