### ISSUE TITLE
Integrated support for bachelor thesis' introductory table

### ISSUE THREAD

**Issue by ruzko** [egraff/uit-thesis#87]
I'm using this template for my bachelor's thesis in mechanical engineering. The thesis requirements includes having a table, as shown below, placed after the title page and before the abstract. Getting this table converted from .docx (which is how it's made available by our course supervisor) to html works well; but conversion to Tex turns out to be complicated and full of errors. Formatting it nicely from scratch might be a bit beyond me as this is the first large document I'm writing with Tex.

Is having integrated support for this table within scope for uit-thesis?

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN" "http://www.w3.org/Math/DTD/mathml2/xhtml-math11-f.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">

<head profile="http://dublincore.org/documents/dcmi-terms/">
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
<title xml:lang="en-US">- no title specified</title>
<meta name="DCTERMS.title" content="" xml:lang="en-US"/>

<meta name="DCTERMS.language" content="en-US" scheme="DCTERMS.RFC4646"/>
<meta name="DCTERMS.source" content="http://xml.openoffice.org/odf2xhtml"/>

<meta name="DCTERMS.issued" content="2024-04-09T13:19:32.007176643" scheme="DCTERMS.W3CDTF"/>

<meta name="DCTERMS.modified" content="2024-04-09T13:19:47.405341067" scheme="DCTERMS.W3CDTF"/>

<meta name="xsl:vendor" content="libxslt"/>
<link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" hreflang="en"/>
<link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" hreflang="en"/>
<link rel="schema.DCTYPE" href="http://purl.org/dc/dcmitype/" hreflang="en"/>
<link rel="schema.DCAM" href="http://purl.org/dc/dcam/" hreflang="en"/>

<style>
    table { border-collapse:collapse; border-spacing:0; empty-cells:show }
    td, th { vertical-align:top; font-size:12pt;}
    h1, h2, h3, h4, h5, h6 { clear:both;}
    ol, ul { margin:0; padding:0;}
    li { list-style: none; margin:0; padding:0;}
    span.footnodeNumber { padding-right:1em; }
    span.annotation_style_by_filter { font-size:95%; font-family:Arial; background-color:#fff000;  margin:0; border:0; padding:0;  }
    span.heading_numbering { margin-right: 0.8rem; }* { margin:0;}
    .paragraph-P1{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-style:italic; }
    .paragraph-P10{ font-size:12pt; line-height:108%; margin-bottom:0cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; margin-left:0cm; margin-right:0cm; text-indent:0cm; }
    .paragraph-P11{ font-size:12pt; line-height:108%; margin-bottom:0cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; margin-left:0cm; margin-right:0cm; text-indent:0cm; }
    .paragraph-P12{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-weight:bold; }
    .paragraph-P13{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-weight:bold; }
    .paragraph-P14{ font-size:11pt; line-height:108%; margin-bottom:0cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; background-color:transparent; margin-left:0.723cm; margin-right:0cm; text-indent:-0.635cm; color:#000000; font-style:normal; text-decoration:none ! important; font-weight:normal; }
    .paragraph-P15{ font-size:11pt; line-height:108%; margin-bottom:0cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; background-color:transparent; margin-left:0cm; margin-right:0cm; text-indent:0cm; color:#000000; font-style:normal; text-decoration:none ! important; font-weight:normal; }
    .paragraph-P16{ font-size:12pt; font-family:'Liberation Serif'; writing-mode:horizontal-tb; direction:ltr;}
    .paragraph-P2{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-style:italic; }
    .paragraph-P3{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-style:italic; font-weight:bold; }
    .paragraph-P4{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-style:italic; font-weight:bold; }
    .paragraph-P5{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; font-style:italic; font-weight:bold; }
    .paragraph-P6{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; }
    .paragraph-P7{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; }
    .paragraph-P8{ font-size:11pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; }
    .paragraph-P9{ font-size:12pt; line-height:108%; margin-bottom:0.282cm; margin-top:0cm; text-align:left ! important; font-family:Calibri; writing-mode:horizontal-tb; direction:ltr; }
    .table-Tabell1{ width:19.039cm; margin-top:0cm; margin-bottom:0cm; 
                margin-left:auto;margin-right:auto;
            writing-mode:horizontal-tb; direction:ltr; }
    .cell-Tabell1_A1{ background-color:transparent; border-top-width:NaNcm; border-top-style:solid; border-top-color:#000000; border-left-width:NaNcm; border-left-style:solid; border-left-color:#000000; border-bottom-width:NaNcm; border-bottom-style:solid; border-bottom-color:#000000; border-right-width:NaNcm; border-right-style:solid; border-right-color:#000000; padding-left:0.191cm; padding-right:0.191cm; padding-top:0cm; padding-bottom:0cm; }
    .col-Tabell1_A{ width:6.438cm; }
    .col-Tabell1_B{ width:7.84cm; }
    .col-Tabell1_C{ width:4.761cm; }
    .text-Internet_20_link{ color:#000080; text-decoration:underline; }
    .text-T10{ font-family:'Liberation Serif'; }
    .text-T11{ font-family:Calibri; }
    .text-T4{ font-style:italic; }
    .text-T5{ font-style:italic; }
    .text-T6{ font-style:italic; font-weight:bold; }
    .text-T7{ font-weight:bold; }
    .text-T8{ font-weight:bold; }
    .text-T9{ font-weight:bold; }
    /* ODF styles with no properties representable as CSS:
    .Tabell1.1 .Tabell1.2 .Tabell1.3 .Tabell1.4 .Tabell1.5 .Tabell1.6 .Tabell1.7 .Tabell1.8 .ListLabel_20_10 .ListLabel_20_11 .ListLabel_20_12 .ListLabel_20_13 .ListLabel_20_14 .ListLabel_20_15 .ListLabel_20_16 .ListLabel_20_17 .ListLabel_20_18 .T1 .T12 .T13 .T2 .T3  { } */
</style>
</head>

<body dir="ltr" style="max-width:21.001cm;margin-top:2cm; margin-bottom:2cm; margin-left:2cm; margin-right:2cm; ">
<p class="paragraph-P16"> </p>

<table border="0" cellspacing="0" cellpadding="0" class="table-Tabell1"><colgroup><col width="281"/><col width="343"/><col width="208"/></colgroup><tr class="row-Tabell1_1"><td colspan="2" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Tittel</p>
<p class="paragraph-P3"> </p>
<p class="paragraph-P6">The title of the thesis</p>
</td><td rowspan="3" style="text-align:left;width:4.761cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Dato:</p>

<p class="paragraph-P4">date of submission of this document</p>

<p class="paragraph-P1">Antall sider: <span class="text-T2">1</span><span class="text-T3">number of pages</span></p>
<p class="paragraph-P1"> </p>
<p class="paragraph-P7"><span class="text-T4">Antall vedlegg: </span><span class="text-T5">number of attachments</span></p>
<p class="paragraph-P9"> </p></td></tr><tr class="row-Tabell1_2"><td style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Emnekode</p>

<p class="paragraph-P5">subject code</p>
</td><td style="text-align:left;width:7.84cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Emnenavn</p>

<p class="paragraph-P12">Hovedprosjekt / bachelor thesis "name-of-course"</p>
</td></tr><tr class="row-Tabell1_3"><td colspan="2" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Forfattere</p>
<p class="paragraph-P15"> </p><ul><li><p class="P14" style="margin-left:0,723cm;"><span class="ListLabel_20_10" style="display:block;float:left;min-width:0.635cm;"></span>name of author(s)<span class="odfLiEnd"/> </p></li></ul></td></tr><tr class="row-Tabell1_4"><td colspan="3" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P7"><span class="text-T4">Fakultet</span>                                                                     Institutt                                                                                                                                                                                     <span class="text-T7">                                                                                                                                                                  </span></p>

<p class="paragraph-P13">name of faculty                               name of institute</p>
</td></tr><tr class="row-Tabell1_5"><td colspan="3" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P8"><span class="text-T4">Veileder:                </span><span class="text-T6">name of mentor</span>                <span class="text-T7">  </span></p>
</td></tr><tr class="row-Tabell1_6"><td colspan="3" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1"><p class="paragraph-P8"><span class="text-T4">Oppdragsgiver:</span> <span> <span class="text-T8"></span><span class="text-T9">Name of customer / industri partner</span></span>

</p></td></tr><tr class="row-Tabell1_7"><td colspan="3" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Sammendrag</p>

<p class="paragraph-P10">summary</p>

<p class="paragraph-P10">Prosjektetslutt:  date of project-end</p>
<p class="paragraph-P10"> </p>
<p class="paragraph-P11"><span class="text-T10">©</span><span class="text-T11"> 2024.</span> copyright if applicable </p>
<p class="paragraph-P10"> </p></td></tr><tr class="row-Tabell1_8"><td colspan="3" style="text-align:left;width:6.438cm; " class="cell-Tabell1_A1">
<p class="paragraph-P1">Stikkord</p>

<p class="paragraph-P2">search terms / word cairns </p>
</td></tr></table>

<p class="paragraph-P16"> </p></body>

</html>

**Comment by ruzko** [comment]
Found a half-good workaround:
1. Open the .docx table document in LibreOffice (or equivalent)
2. fill with correct information
3. Export as single-page pdf
4. place pdf of table in same directory as .tex document (or subdir)
5. in tex preamble, `\usepackage{pdfpages}`
6. in tex frontmatter, `\includepdf[pages=-]{relative/path/to/table.pdf}`


PS. I forgot to add the table .pdf file in the issue at first, for accurate depiction. Here it is.
[tabell_ren.pdf](https://github.com/egraff/uit-thesis/files/15074937/tabell_ren.pdf)

**Comment by egraff** [comment]
> Is having integrated support for this table within scope for uit-thesis?

I'm afraid it would not be in scope, because the requirements are too specific to this particular course/studies.

Your workaround actually does sound sensible, as doing this table in LaTeX is _very_ fiddly. However, I did an attempt at what it could look like, but I'm pretty sure the spacing is a bit messed up or inconsistent at least.

```latex
\documentclass[noprint]{uit-thesis}

\usepackage{multirow}
\usepackage{lipsum}

\begin{document}

\newgeometry{
  left=0.5in,
  right=0.5in
}

\cleardoublepage
\thispagestyle{empty}
\pagenumbering{Alph}
\setcounter{page}{3}

\newlength\wColA
\setlength\wColA{2.0in}
\newlength\wColB
\setlength\wColB{\dimexpr 0.5\linewidth - \wColA - 4\tabcolsep - 2\arrayrulewidth\relax}
\newlength\wColD
\setlength\wColD{1.6in}
\newlength\wColC
\setlength\wColC{\dimexpr 0.5\linewidth - \wColD - 4\tabcolsep - 2\arrayrulewidth\relax}

\newlength\wColAB
\setlength\wColAB{\dimexpr\wColA+\wColB+2\tabcolsep+\arrayrulewidth\relax}
\newlength\wColABC
\setlength\wColABC{\dimexpr\wColA+\wColB+\wColC+4\tabcolsep+2\arrayrulewidth\relax}
\newlength\wColABCD
\setlength\wColABCD{\dimexpr\wColA+\wColB+\wColC+\wColD+6\tabcolsep+3\arrayrulewidth\relax}
\newlength\wColBC
\setlength\wColBC{\dimexpr\wColB+\wColC+2\tabcolsep+\arrayrulewidth\relax}
\newlength\wColCD
\setlength\wColCD{\dimexpr\wColC+\wColD+2\tabcolsep+\arrayrulewidth\relax}


{%
  \renewcommand{\arraystretch}{1.5}
  \begin{tabular}[t]{|p{\wColA}p{\wColB}p{\wColC}p{\wColD}|}
    \hline
    \multicolumn{3}{|p{\wColABC}|}{%
      \begin{minipage}[t]{\wColABC}
        Tittel\\[2\baselineskip]
        x\\
      \end{minipage}
    } & \multirow[t]{3}{*}{
      \begin{minipage}[t]{\wColD}
        Dato:\\

        Antall sider:\\

        Antall vedlegg:
      \end{minipage}
    }\\
    \cline{1-3}
    \multicolumn{1}{|p{\wColA}}{%
      \begin{minipage}[t]{\wColA}
        Emnekode\\[\baselineskip]
        x\\
      \end{minipage}
    } & \multicolumn{2}{|p{\wColBC}|}{%
      \begin{minipage}[t]{\wColBC}
        Emnenavn\\[\baselineskip]
        x\\
      \end{minipage}
    } & \\
    \cline{1-3}
    \multicolumn{3}{|p{\wColABC}|}{%
      \begin{minipage}[t]{\wColABC}
        Forfattere\\[2\baselineskip]
        x\\
      \end{minipage}
    } & \\
    \hline
    \multicolumn{2}{|p{\wColAB}}{%
      \begin{minipage}[t]{\wColAB}
        Fakultet\\[\baselineskip]
        x\\
      \end{minipage}
    } & \multicolumn{2}{|p{\wColCD}|}{%
      \begin{minipage}[t]{\wColCD}
        Institutt\\[\baselineskip]
        x\\
      \end{minipage}
    }\\
    \hline
    \multicolumn{4}{|p{\wColABCD}|}{%
      \begin{minipage}[t]{\wColABCD}
        Veileder:\hspace{0.8in}x\\
      \end{minipage}
    }\\
    \hline
    \multicolumn{4}{|p{\wColABCD}|}{%
      \begin{minipage}[t]{\wColABCD}
        Oppdragsgiver:\hspace{0.38in}x\\
      \end{minipage}
    }\\
    \hline
    \multicolumn{4}{|p{\wColABCD}|}{%
      \begin{minipage}[t]{\wColABCD}
        Sammendrag:\\[\baselineskip]
        x\\[5\baselineskip]
      \end{minipage}
    }\\
    \hline
    \multicolumn{4}{|p{\wColABCD}|}{%
      \begin{minipage}[t]{\wColABCD}
        Stikkord:\\[\baselineskip]
        x\\[2\baselineskip]
      \end{minipage}
    }\\
    \hline
  \end{tabular}
}


\restoregeometry

\cleardoublepage
\pagenumbering{arabic}
\setcounter{page}{1}

\lipsum[1-4]

\end{document}
```
