### ISSUE TITLE
Longer description for acrynoms

### ISSUE THREAD

**Issue by ruzko** [egraff/uit-thesis#89]
My thesis has quite a few acronyms for complicated things that should have should have proper explanations, like VLAN and mAP50-95.

Since there are a number of them and submission date is in five days, I'd prefer not having to manually define `\newacronym` as well as `\newglossaryentry` for each of them.

I haven't found any relevant style guides for how this should be done, but have got some ideas.
Ideally, I'd want acronyms which fulfill some condition (contains explanation in a certain field) to automatically have their long form and explanation included in the printed `\printglossary`. Either by default or with a toggle.
Looking at `ult-base/ult-glossaries.sty`, It seems the best place to define that explanation is in the `text` field. 

This could be achieved with a command that dynamically creates / updates glossary entries based on acronym entries with text in given fields.

Inversely, this would also be great: glossaryentries with `short` key have their `short` and `name` field automatically included in the printed `\printacronyms`. However, the [glossaries user manual, page 136](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.pdf) state that the `long` option is reserved for `\newacronym`, so this might be unreliable. A more robust method is adding a custom value  in the `userkey1` field or with `\glsaddstoragekey`.

Example:

```latex
\documentclass[norsk,noprint]{uit-thesis}

\makeglossaries

\newacronym[text={
	Lar en vert konfigurere nettverksinnstillingene til andre verter i nettverket. I mange hjemmenettverk fyller ruteren rolle som DHCP-tjener.
	}]{dhcp}{DHCP}{Dynamic Host Configuration Protocol}

\newglossaryentry{mp}
{
	name=multiprosessering,
	userkey1=mp,
	description={
		Metode hvor et program gjør nytte av flere prosesser samtidig.
	}
}

\begin{document}

here's \ac{dhcp} and its counterpart \gls{mp}.

\printacronyms
\printglossary

\end{document}

```

Do you have any advice to tide me over for now, and what do you think of this?

**Comment by ruzko** [comment]
After some more searching, I found that the `glossaries` manual covers this usecase on page 256, with the custom command \dualentries.
```latex
\newcommand*{\newdualentry}[5][]{%
    \newglossaryentry{main-#2}{name={#4},%
    text={#3\glsadd{#2}},%
    description={#5},%
    #1
    }%
    \newacronym{#2}{#3\glsadd{main-#2}}{#4}%
}

```
Could uit-thesis maybe carry this as a built-in command?

**Comment by egraff** [comment]
If I understand you correctly (please correct me if I'm wrong 🙂), you want to be able to:
 1) Print an acronym list as normal, without any modifications
 2) Print a (different) glossary list, but include _some_ of the acronyms for which certain criteria is met

My first question would be if you _do_ in fact have glossary entries in the second list that are not acronyms (i.e. they are not present in the acronym list). And, depending on the answer to that question, my follow-up question would be if you are sure you want the "special" acronyms to show up in both lists, or if you rather would want some extra details shown in the acronym list for the special acronyms, to avoid having them duplicated in both lists.

The reason I ask is that there is a lot of flexibility in defining custom glossary styles, where you can display entries in the list differently depending on how the acronym or glossary entries are defined.

> Could uit-thesis maybe carry this as a built-in command?
I think your use-case is too much of a special case for this to be provided by the uit-thesis document class itself 😉

**Comment by egraff** [comment]
Right 🙂 I think your use case is absolutely a valid and good one - my concern is more how to standardize on exactly how to display it 😉 like you say, there are multiple ways of approaching this, and different authors may have preferences for one or the other.

I think the solution you found with dual entries sounds like it could work fine for your case 🙂 but let me comment on both of the two cases you outlined:

1) > If each "acronym where the long form needs explanation" could have up to three lines of explanatory text in the acronym list, I think that might be the most elegant solution.

and

2) > Alternatively, if the duplication style better suits the UiT style guide, I'd like to crosslink between corresponding entries in the acronym and glossary lists.

I think both these cases could be solved by adding a custom _glossary style_ (not to be confused with _acronym style_), which basically is what defines how a list-of-acronyms/glossary is displayed. The `uit-thesis` document class actually has its own glossary styles, but only with minor formatting tweaks (so it's not a good starting point for you to look at):

https://github.com/egraff/uit-thesis/blob/5537652b90769b23b73a7e6897c4a9c3a634ecfd/texmf-tds/tex/latex/uit-thesis/uit-thesis.cls#L1067-L1105)

so `\printacronyms` is actually redefined as `\printglossary[type=\acronymtype,style=ult-list]`.

From the glossaries user manual, I would look at example 24 on page 331-333, example 35 on page 333, or the example in section 4.3.2 (page 141, example on page 147). Note especially the use of `\ifglshassymbol` in the example on page 333 - you may use any other if-test macro as appropriate, for example `\ifglshasdesc` or `\ifglshaslong`, or - if you want to test for e.g. the user1 key -`\ifglshasfield{useri}`. See the mapping on page 148 and the commands around page 633 for reference.

For case 1), you should probably start by finding an appropriate display style that would look good if you were to have a description spanning multiple lines, and base your style off of that (it could be that there are better ones than `list` and `long` - the glossaries packages come with a bunch of styles to pick from). It shouldn't be too hard to use an if-test to check if an acronym has a "long description" (e.g. by using the user1 key or something similar to contain the long description if it exists), and determine what is displayed based on that.

For case 2), if you want to cross-link both from an entry in the acronym list to the glossary list and vice versa, you might need to define two display styles (unless you do something clever, where you in the definition of your glossary style first determine if it is a glossary or a list-of-acronyms, and "branch off" the logic for what to link to based on this). In the display style for the list-of-acronyms, you could have an if-test to check if there is a corresponding entry in the glossary and if so add a hyperlink, and similarly in the display style for the glossary conditionally add a hyperlink to a corresponding acronym. I'm not exactly sure how to add the link, but I'm sure it's doable.

**Comment by egraff** [comment]
Closing this issue after no response. Hope you got something working in the end 🙂
