### ISSUE TITLE
Support for Overleaf

### ISSUE THREAD

**Issue by FilippoMB** [egraff/uit-thesis#90]
Hi,

most of our students are using Overleaf to write the thesis. Is there a version of this template that works on Overleaf?

Thanks (❁´◡`❁)

**Comment by NilsBochow** [comment]
I used it on Overleaf, it worked for me without bigger complications.

**Comment by FilippoMB** [comment]
Great, thanks 🙏.

What is the way of doing it? Start an empty project on Overleaf and copy on the root the content of `/uit-thesis/tree/master/texmf-tds/tex/latex/uit-thesis`?

Would be nice to have a link to an Overleaf template in the README of this repo maybe @egraff ?

**Comment by NilsBochow** [comment]
> What is the way of doing it? Start an empty project on Overleaf and copy on the root the content of /uit-thesis/tree/master/texmf-tds/tex/latex/uit-thesis? 

Exactly

**Comment by egraff** [comment]
Overleaf is supported to the extent that the chosen TeX Live version used to compile the document is supported (Overleaf supports several versions) 🙂 there won't be an "official" Overleaf template, as there doesn't seem to be a clear way of achieving that (and if there was, it would probably be a lot of effort to support it / make sure it continues to work) 😉
