### ISSUE TITLE
Spacing around theorems

### ISSUE THREAD

**Issue by koen-vg** [egraff/uit-thesis#91]
Hi, and thanks again for the great package.

I've noticed that spacing around `amsthm` environments seems a little messed up. See the following example:

```latex
\theoremstyle{definition}
\newtheorem{definition}{Definition}

[...]

\lipsum[1][1-4]

\begin{definition}
  An interesting definition
\end{definition}

\lipsum[2][1-4]

\setlength{\topsep}{10pt}

\lipsum[1][1-4]

\begin{definition}
  An interesting definition
\end{definition}

\lipsum[2][1-4]
```
![Skjermbilde fra 2024-06-09 11-56-29](https://github.com/egraff/uit-thesis/assets/74298901/84ad0945-f82c-4571-95c5-d89f39b72639)

Certainly, the lack of any gap between a paragraph and the subsequent definition isn't how the definition environment is supposed to work. As demonstrated, it seems `\topsep` being set to 0 somehow is the culprit (see its use [here](https://github.com/tlaplus/tlapm/blob/main/doc/arqnl14/amsthm.sty). But setting `\topsep` to the default of around 10pt makes the spacing below the environment too large.

I couldn't quite figure out what's going on the the uit-thesis class. `\topsep` is modified here:
```latex
% Spacing for \item lists
% \topsep is vertical spacing before first item
% \parsep is spacing between items
% \itemsep = \z@ <=> add nothing to \parsep between items
\def\@listI{%
  \leftmargin\leftmargini
  \topsep\ult@normalbaselineskip
  \advance\topsep by -\parskip
  \parsep\parskip
  \listparindent\parindent
  \itemsep\z@
}
\let\@listi\@listI
\@listi
```
But when commenting this out, `\topsep` is still 0.

I will note that `amsthm` in loaded by `uit-thesis.cls`, so nominally I would expect compatibility.

Ideas?

P.S. for anyone else finding this problem, the best adhoc solution I have found is to just manually add some spacing, or defining my own theoremstyle instead of using the built-in definition (or other) style.

**Comment by egraff** [comment]
Hi, @koen-vg, and thanks for the report! This seems a bit peculiar 🤔 I don't have any immediate suspicions as to where this problem comes from, but I'll try to have a look when I have some available time 🙂

Do you mind if I use your example code for reproducing the problem as the basis for a test, once I (hopefully) find and fix the culprit?

**Comment by koen-vg** [comment]
Feel more than free to use my example for any purpose; consider it in the public domain.

**Comment by egraff** [comment]
Thank you! 🙂

Good news is that it looks like I've identified the problem. I just need to generate new test prototypes for all supported versions of Tex Live, and run the tests to make sure it works as expected.
